Легкие изменения переводов фраз фигурок
space-sunrise/lust-station pull request #94
Opened 2024-11-28 12:59 UTC by Kinar7

## Кратное описание
Исправление перевода фраз фигурок

## По какой причине
Переводчики дословно перевили фразу "Grey tide station wide!", получилось "Серая Волна по всей станции". Что звучит пздц как не логично. По этому я считаю что нужно исправить на "Грей Тайд по всей станции
А Элитный Оперативник кричит про Нанотрейзен, хотя по идее должен пол Qillu

## Проверки

- [ ] Я не требую помощи для завершения PR
- [ ] Перед выкладыванием/запросом о рассмотрении PR, Я проверил работоспособность изменений.
- [ ] Я добавил скриншоты/видео изменений, или данный PR не меняет внутриигровые механики

**Changelog**
Изменение переводов фраз фигурок

2024-11-29 01:42 UTC, VigersRay requested changes

2024-11-29 01:42 UTC, VigersRay commented on Resources/Locale/ru-RU/_strings/datasets/figurines.ftl
> +figurines-greytider-5 = Грей Тайд по всей станции!
Это уже было изменено на санрайзе, здесь нет смысла.

2024-11-29 01:42 UTC, VigersRay commented on Resources/Locale/ru-RU/_strings/datasets/figurines.ftl
> +figurines-nukie-elite-1 = Ни слова в Qillu.
нет-нет-нет. Хватит создавать конфликты в локализации. 
Если вы хотите заменить во всем мире слово Nanotrasen на Qillu стоит реализовать этот функционал автоматически при помощи интеграции с системой локализации.
Ибо это ни в какие ворота уже.

2024-11-29 06:16 UTC, Kinar7 commented on Resources/Locale/ru-RU/_strings/datasets/figurines.ftl
> +figurines-nukie-elite-1 = Ни слова в Qillu.
Понял

2024-11-30 07:32 UTC, pxc1984 commented
closed (see review from @VigersRay )

2024-11-30 07:32 UTC, closed without merging